package ligai.enums;

public enum QuestionType {
    ONE_OUT_OF_FOUR, MULTIPLE_OUT_OF_FOUR, ONE_OUT_OF_FOUR_PIC, MULTIPLE_OUT_OF_FOUR_PIC,
    PAIRS, PAIRS_PIC, GROUP, GROUP_PIC,
    SEQUENCE, SEQUENCE_INCERT, SEQUENCE_INCERT_NOGAPS, SEQUENCE_PRINT, SEQUENCE_OUT,
    TEXT
}
